config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_in' => 'devise/sessions#new'
  end

  resources :likes
  resources :favorites
  resources :images do
    collection do
      get 'getpic'
    end
  end
  resources :events do
    collection do
      get 'nearby'
      get 'search'
    end
  end

  match 'users', to: 'users#index', via: [:options]
  resources :users
  resources :performers

  resources :places do
    collection do
      get 'nearby'
    end
  end

  post 'users/:id/like' => 'users#like'

  get '/users', :to => 'users#index'
  get '/events', :to => 'events#index'
  get '/performers', :to => 'performers#index'
  get '/places', :to => 'places#index'

  root :to => 'pages#home'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :image_link, polymorphic: true
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getpic
    @images = Image.where(nil)
    @images = @images.where(image_link_type: params[:imtype]) if params[:imtype].present?
    @images = @images.where(image_link_id: params[:imid]) if params[:imid].present?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image_link_type, :image_link_id, :url_image)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_link_type %><br>
    <%= f.text_field :image_link_type %>
  </div>
  <div class="field">
    <%= f.label :image_link_id %><br>
    <%= f.number_field :image_link_id %>
  </div>
  <div class="field">
    <%= f.label :url_image %><br>
    <%= f.text_field :url_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Image link type</th>
      <th>Image link id</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.image_link_type %></td>
        <td><%= image.image_link_id %></td>
        <td><%= image.url_image %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image link type:</strong>
  <%= @image.image_link_type %>
</p>

<p>
  <strong>Image link id:</strong>
  <%= @image.image_link_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @image.url_image %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>