config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_in' => 'devise/sessions#new'
  end

  resources :likes
  resources :favorites
  resources :images do
    collection do
      get 'getpic'
    end
  end
  resources :events do
    collection do
      get 'nearby'
      get 'search'
    end
  end

  match 'users', to: 'users#index', via: [:options]
  resources :users
  resources :performers

  resources :places do
    collection do
      get 'nearby'
    end
  end

  post 'users/:id/like' => 'users#like'

  get '/users', :to => 'users#index'
  get '/events', :to => 'events#index'
  get '/performers', :to => 'performers#index'
  get '/places', :to => 'places#index'

  root :to => 'pages#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_one :place
  has_one :performer
  has_many :images, as: :image_link


  scope :cheaper_than, ->(chp) {where("price <= ?", "#{chp}") }
  scope :categoryE, -> (cat) { where(performer_id: Performer.category(cat)) }
  scope :genreE, -> (gnr) { where(performer_id: Performer.genre(gnr)) }



  acts_as_mappable :through => :place
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorite_link, polymorphic: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :image_link, polymorphic: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :like_link, polymorphic: true
end

app/models/performer.rb
class Performer < ActiveRecord::Base
  belongs_to :event
  has_many :images, as: :image_link
  has_many :favorites, as: :favorite_link
  has_many :likes, as: :like_link

  scope :category, -> (cat) { where("performer_category LIKE ?", "%#{cat}%") }
  scope :genre, -> (gnr) { where("genre LIKE ?", "%#{gnr}%") }
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :event
  has_many :images, as: :image_link
  has_many :favorites, as: :favorite_link
  has_many :likes, as: :like_link

  acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes
  has_many :favorites

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def nearby
    distance = params[:distance] || 1
    @events = Event.where(place_id: Place.within(distance, :units => :kms, :origin => [params[:latitude], params[:longitude]])).where(date: Date.current..(Date.current + 1.days))
  end

  def search
    distance = params[:distance] || 1
    @events = Event.where(nil)
    @events = @events.categoryE(params[:cat]) if params[:cat].present?
    @events = @events.genreE(params[:gnr]) if (params[:gnr].present? and params[:cat]=="Musician")
    @events = @events.cheaper_than(params[:chp]) if params[:chp].present?
    @events = @events.where(place_id: Place.within(distance, :units => :kms, :origin => [params[:latitude], params[:longitude]])) if (params[:distance].present? and params[:latitude].present? and params[:longitude].present?)
    @events = @events.where(date: params[:date]..(params[:date] + 1.days)) if params[:date].present?
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :place_id, :performer_id, :description, :date, :price)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:user_id, :like_link_type, :like_link_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/performers_helper.rb
module PerformersHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
  <footer class="footer">
    <p>&copy; FunkEvent 2015</p>
  </footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">

    <a class="navbar-brand" href="/"> <%= image_tag("logo.png", alt: "Funkevent logo") %></a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Users", users_path  %></li>
        <li><%= link_to "Events", events_path  %></li>
        <li><%= link_to "Performers", performers_path  %></li>
        <li><%= link_to "Places", places_path  %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
<![endif]-->

<!-- For third-generation iPad with high-resolution Retina display: -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FunkEvent" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>


    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <%= render 'layouts/footer' %>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/home.html.erb
<h1>FunkEvent</h1>
<p>Home page of FunkEvent, the app that will help you find new bands and events around you! </p>

<%= link_to "Sign up", 'users/new', :class => "signup_button round" %>